use_map_topic: true
min_particles: 100
max_particles: 5000
kld_err: 0.05
kld_z: 0.99
update_min_d: 0.2
update_min_a: 0.2
odom_model_type: "diff"
odom_alpha1: 0.2
odom_alpha2: 0.2
odom_alpha3: 0.2
odom_alpha4: 0.2
laser_model_type: "likelihood_field"
laser_z_hit: 0.9
laser_z_short: 0.1
laser_z_max: 0.05
laser_z_rand: 0.05
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
